### ISSUE TITLE
aar not found in version 1.5.0

### ISSUE THREAD

**Issue by h03ein1376** [SirLordPouya/PersianLinearDatePicker#3]
i have issue with version 1.5.0 and error :
Could not find PersianLinearDatePicker-1.5.0.aar 

version 1.3.0 worked fine

**Comment by HeyPouya** [comment]
It should be fixed in version 1.6.0.

Please let me know if it fixes your issue.

**Comment by h03ein1376** [comment]
that fixed 
thanks for your attention♥
